# GENERAL SETUP ---
TMPDIR: /mnt/nvme_raid0/tmp
CORES: 8
CONDA_ROOT: /opt/conda/miniconda3
DOCKER_DATA_DIR: /home

# GENCODE ---
GENCODE:
    SPECIES: hsapiens
    # hsapiens | mmusculus
    VERSION: "37"
    # 32 | M23
    GENOME: GRCh38.primary_assembly
    # GRCh38.primary_assembly | GRCm38.primary_assembly
    ANNOTATION: primary_assembly.annotation
    # primary_assembly.annotation | basic.annotation
